version: "3.7"
services:
  oidc-provider:
    container_name: oidc-provider-personopplysninger
    image: "docker.pkg.github.com/navikt/stub-oidc-provider/stub-oidc-provider:latest"
    ports:
      - "9000:9000"
    environment:
      PORT: "9000"
      CALLBACK_URL: "http://localhost:5000/callback"
      ISSUER: "https://localhost:9000"

  oidc-provider-gui:
    container_name: oidc-provider-gui-personopplysninger
    image: "docker.pkg.github.com/navikt/pb-oidc-provider-gui/pb-oidc-provider-gui:latest"
    ports:
      - "5000:5000"
    environment:
      REDIRECT_URL: "http://localhost:3000"
      AUTO_REDIRECT_TO_FRONTEND: "true"
    depends_on:
      - oidc-provider

  mocks:
    container_name: mocks-personopplysninger
    image: "docker.pkg.github.com/navikt/pb-nav-mocked/pb-nav-mocked:latest"
    ports:
      - "8095:8080"
    environment:
      CORS_ALLOWED_ORIGINS: "*"
      OIDC_ISSUER: "https://localhost:9000"
      OIDC_ACCEPTED_AUDIENCE: "stubOidcClient"
      OIDC_JWKS_URI: "http://oidc-provider:9000/certs"
      KAFKA_BOOTSTRAP_SERVERS: "http://localhost:5121"
      KAFKA_SCHEMAREGISTRY_SERVERS: "http://localhost:5121"
    depends_on:
      - oidc-provider

  dekoratoren:
    container_name: dekoratoren-personopplysninger
    image: "docker.pkg.github.com/navikt/nav-dekoratoren/nav-dekoratoren:latest"
    ports:
      - "8100:8088"
    environment:
      XP_BASE_URL: "http://localhost:3000"
      APP_BASE_URL: "http://localhost:8100"
      APP_BASE_PATH: "/dekoratoren"
      API_XP_SERVICES_URL: "https://www.nav.no/_/service"
      API_INNLOGGINGSLINJE_URL: "http://localhost:8095/innloggingsstatus"
      API_VARSELINNBOKS_URL: "http://mocks:8080/person/varselinnboks"
      MINSIDE_ARBEIDSGIVER_URL: "http://localhost:8080/min-side-arbeidsgiver/"
      DITT_NAV_URL: "http://localhost:8080/minside/"
      LOGIN_URL: "http://localhost:5000"
      LOGOUT_URL: "http://localhost:5000/?logout"
    depends_on:
      - mocks

  arbeidsforhold-api:
    container_name: arbeidsforhold-api-personopplysninger
    image: "navikt/arbeidsforhold-api:5ae21ce5-987b-4da2-8027-077c93564195-v1.0.17"
    ports:
      - "8096:8080"
    environment:
      APP_LOG_HOME: "target/log"
      contextName: "arbeidsforhold-api"
      AAD_B2C_ISSUER: "https://localhost:9000"
      AAD_B2C_CLIENTID_USERNAME: "stubOidcClient"
      AAD_B2C_DISCOVERY_URL: "http://oidc-provider:9000/.well-known/openid-configuration"
      KODEVERK_REST_API_URL: "http://mocks:8080/kodeverk/api/"
      ARBEIDSFORHOLD_API_KODEVERK_REST_API_APIKEY_USERNAME: "x-nav-apiKey"
      ARBEIDSFORHOLD_API_KODEVERK_REST_API_APIKEY_PASSWORD: "dummy-token"
      EREG_API_URL: "http://mocks:8080/ereg/api/"
      ARBEIDSFORHOLD_API_EREG_API_APIKEY_USERNAME: "x-nav-apiKey"
      ARBEIDSFORHOLD_API_EREG_API_APIKEY_PASSWORD: "dummy-token"
      SECURITY_TOKEN_SERVICE_TOKEN_URL: "http://mocks:8080/security-token-service/rest/v1/sts/token/"
      ARBEIDSFORHOLD_API_SECURITY_TOKEN_SERVICE_TOKEN_APIKEY_USERNAME: "x-nav-apiKey"
      ARBEIDSFORHOLD_API_SECURITY_TOKEN_SERVICE_TOKEN_APIKEY_PASSWORD: "dummy-token"
      AAREG_API_URL: "http://mocks:8080/aareg-services/api/"
      ARBEIDSFORHOLD_API_AAREG_API_APIKEY_USERNAME: "x-nav-apiKey"
      ARBEIDSFORHOLD_API_AAREG_API_APIKEY_PASSWORD: "dummy-token"
      SRVARBEIDSFORHOLD_API_USERNAME: "srvarbeidsforhold-"
      SRVARBEIDSFORHOLD_API_PASSWORD: "dummy-password"
    depends_on:
      - oidc-provider
      - mocks

volumes:
  event-cache-data:
