---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: personopplysninger
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /person/personopplysninger/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/personopplysninger/internal/isReady
    initialDelay: 10
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: false
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        {{#each externalHosts as |host|}}
        - host: {{host}}
        {{/each}}
  {{#with replicas}}
  replicas:
    min: {{min}}
    max: {{max}}
  {{/with}}
  {{#with resources}}
  resources:
    requests:
      cpu: {{requests.cpu}}
      memory: {{requests.memory}}
    limits:
      memory: {{limits.memory}}
  {{/with}}