---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: personopplysninger
  namespace: min-side
  labels:
    team: min-side
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://www.intern.nav.no/person/personopplysninger"
  liveness:
    path: /person/personopplysninger/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/personopplysninger/internal/isReady
    initialDelay: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: false
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        {{#each externalHosts as |host|}}
        - host: {{host}}
        {{/each}}
  env:
    - name: ENV
      value: {{env}}
  {{#with replicas}}
  replicas:
    min: {{min}}
    max: {{max}}
  {{/with}}
  {{#with resources}}
  resources:
    requests:
      cpu: {{requests.cpu}}
      memory: {{requests.memory}}
    limits:
      memory: {{limits.memory}}
  {{/with}}