import merInfo from "./nb/informasjon";
/* tslint:disable */
export default {
  "side.tittel": `Personopplysninger`,
  "side.tilbake": "Tilbake",
  "side.slett": "Slett",
  "side.bekreft": "Bekreft",
  "side.lagre": "Lagre",
  "side.avbryt": "Avbryt",
  "side.leggtil": "Legg til",
  "side.valgfritt": " (valgfritt)",
  "side.organisasjonsnummer": "Organisasjonsnummer {orgnr}",
  "side.endre": "Endre",
  "side.endre.alle.opplysninger": "Endre opplysninger",
  "side.endre.kontaktinformasjon": "Endre kontaktinformasjon",
  "side.endre.adresser": "Endre adresser",
  "side.endre.kontonummer": "Endre kontonmmer",
  "side.endretil": "Endre til",
  "brodsmulesti.dittnav": `Ditt NAV`,
  "brodsmulesti.dinepersonopplysninger": `Personopplysninger`,
  "brodsmulesti.arbeidsforhold": `Arbeidsforhold`,
  "header.hello": `Hei {name}!`,
  "header.description": `<a href='https://www.nav.no/personvern' target='blank' rel='noopener noreferrer' class='lenke'>Les om personvern i Arbeids- og velferdsetaten her.</a>`,
  "header.obs": `Her kan du se opplysninger som NAV har registrert om deg. Du har rett til innsyn i personopplysninger NAV har registrert om deg, men det er ikke sikkert du finner alle personopplysninger her. Det kan skyldes både tekniske og juridiske begrensninger.`,
  "personalia.tittel": `Personalia`,
  "personalia.beskrivelse": `Vi må vite hvem du er og hvordan vi kan kontakte deg. Hvis du skal ha tjenester eller søker om økonomisk støtte, trenger vi opplysninger for å kunne vurdere hva du har krav på. For å kunne utbetale penger trenger vi kontonummeret ditt og en adresse.`,
  "personalia.first_name": `Fornavn`,
  "personalia.first_and_middle_name": `For- og mellomnavn`,
  "personalia.surname": `Etternavn`,
  "personalia.fnr": `Fødselsnummer`,
  "personalia.dnr": `D-nummer`,
  "personalia.foreign_id": `Utenlandsk ID`,
  "personalia.email": `E-post`,
  "personalia.language": `Språk`,
  "personalia.citizenship": `Statsborgerskap`,
  "personalia.status": `Personstatus`,
  "personalia.birthplace": `Fødested`,
  "personalia.spesreg": `Spesialregistrering`,
  "personalia.civil_status": `Sivilstand`,
  "personalia.security_measure": `Sikkerhetstiltak`,
  "personalia.gender": `Kjønn`,
  "personalia.customized_comm": `Tilpasset kommunikasjon`,
  "personalia.source.folkeregisteret": `Kilde: Folkeregisteret`,
  "personalia.source.nav": `Kilde: NAV`,
  "personalia.source.dkif": `Kilde: Kontakt - og reservasjonsregisteret`,
  "personalia.link.folkeregisteret": `Endre i Folkeregisteret`,
  "personalia.link.brukerprofil.endre": `Endre i Din profil`,
  "personalia.link.brukerprofil.leggtil": `Legg til i Din profil`,
  "personalia.link.dkif.endre": `Endre i Kontakt- og reservasjonsregisteret `,
  "personalia.link.dkif.leggtil": `Gå til Kontakt- og reservasjonsregisteret `,
  "personalia.kontonr": `Kontonummer`,
  "personalia.iban": `IBAN`,
  "personalia.kontonrelleriban": `Kontonummer / IBAN`,
  "personalia.kontonr.oveskrift": `Kontonummer vi utbetaler til`,
  "personalia.kontonr.ingenData": `Vi har ikke registrert kontonummer på deg. <br>Du kan registrere kontonummer ved å trykke på «Legg til»`,
  "personalia.bank": `Bank`,
  "personalia.valuta": `Valuta`,
  "personalia.bickode": `BIC / SWIFT-kode`,
  "personalia.bankkode": `Bankkode`,
  "personalia.tlfnr": `Telefon`,
  "personalia.tlfnr.oveskrift": `Telefonnummer registrert hos NAV`,
  "personalia.tlfnr.ingenData": `Vi har ikke registrert telefonnummer på deg i våre registre. <br>Har du et telefonummer vi kan kontakte deg på?`,
  "personalia.tlfnr.arbeid": `Arbeid`,
  "personalia.tlfnr.mobil": `Mobil`,
  "personalia.tlfnr.hjem": `Hjem`,
  "personalia.tlfnr.slett.alert": `Er du sikker på at du vil fjerne dette nummeret?`,
  "personalia.dkif.overskrift": `Opplysninger fra Kontakt - og reservasjonsregisteret`,
  "personalia.dkif.beskrivelse": `Kontakt- og reservasjonsregisteret er et felles nasjonalt register. NAV må ha dine kontaktopplysninger i dette registeret for å kunne sende deg meldinger og dokumenter elektronisk.`,
  "personalia.dkif.kanVarsles": `Du har <b>ikke</b> reservert deg mot elektronisk kommunikasjon.`,
  "personalia.dkif.kanIkkeVarsles": `Du har reservert deg mot elektronisk kommunikasjon.`,
  "personalia.dkif.ingenData": `Ingen opplysninger registrert`,
  "adresse.tittel": `Adresser`,
  "adresse.beskrivelse": `Her finner du bostedsadresse og eventuelt din midlertidige adresse.`,
  "adresse.bostedsadresse": `Bostedsadresse`,
  "adresse.bostedsadresse.apneTekst": `Vis detaljer`,
  "adresse.bostedsadresse.lukkTekst": `Skjul detaljer`,
  "adresse.midlertidigadresse": `Midlertidig adresse`,
  "adresse.midlertidigadresse.leggtil.beskrivelse": `Du har ikke registrert en midlertidig adresse. <br>Hvis du ønsker å få post fra NAV til en midlertidig adresse, kan du registrere adressen.`,
  "adresse.utenlandskadresse": `Midlertidig adresse i utlandet`,
  "adresse.utenlandskadresse.leggtil.beskrivelse": `Du har ikke registrert en midlertidig adresse. <br>Hvis du ønsker å få post fra NAV til en midlertidig adresse, kan du registrere adressen. `,
  "adresse.postadresse": `Postadresse`,
  "adresse.adressetillegg": `Adressetillegg`,
  "adresse.gate": `Gate`,
  "adresse.postnummer": `Postnummer`,
  "adresse.poststed": `Poststed`,
  "adresse.dato": `Flyttedato`,
  "adresse.kommune": `Kommune`,
  "adresse.bolignummer": `Bolignummer`,
  "adresse.land": `Land`,
  "adresse.overskrift": `Adresser som er registert i Folkeregisteret`,
  "adresse.ikke.registrert": `Du har ikke registrert bostedsadresse i Folkeregisteret`,
  "adresse.midlertidig.alert": `Frem til og med {dato} sender vi deg post til din midlertidige adresse.`,
  "adresse.slett.alert": `Vil du fjerne den midlertidige adressen og bruke folkeregistrert </br> adresse til å motta post fra NAV?`,
  "adresse.hjelpetekster.adressetyper": `<p>Postadresse inneholder gatenavn, gatenummer og postnummer.</p><p>Postboksadresse viser til en postboks på et postkontor eller post i butikk.</p><p>Stedsadresse viser til et sted, for eksempel en gård, og inneholder ikke gatenavn</p>`,
  "adresse.hjelpetekster.gyldigtil": `<p>Du velger selv hvor lenge adressen skal være gyldig, maksimalt 1 år. Etter 1 år må du endre eller forlenge adressen.</p>`,
  "adresse.hjelpetekster.co": `<p>Bor du midlertidig på en annen persons adresse og ønsker posten dit? Da må posten være merket med den andre personens navn. Det er ekstra viktig hvis navnet ditt ikke står på postkassen.</p>`,
  "adresse.hjelpetekster.bolignummer": `<p>Bolignummer er en del av adressen hvis du bor i leilighet i et flerbolighus.</p>`,
  "adresse.hjelpetekster.utenlandsk.adresse": `<p>Vær nøye med å fylle ut riktig adresse slik at posten kommer fram. Du kan dele adressen over flere linjer, inntil 30 tegn per linje.</p>`,
  "arbeidsforhold.tittel": `Arbeidsforhold`,
  "arbeidsforhold.beskrivelse": `<p>NAV trenger informasjon om arbeidsforholdene dine for å kunne vurdere behovet ditt for oppfølging og tjenester fra NAV, og til å beregne hvor mye du kan få utbetalt i for eksempel sykepenger, dagpenger og foreldrepenger. Andre offentlige etater har også tilgang til opplysninger fra Arbeidsgiver og arbeidstakerregisteret.</p><p>Det er Arbeids- og velferdsetaten som eier og forvalter Arbeidsgiver og arbeidstakerregisteret (Aa-registeret).<br/><a href="https://www.nav.no/no/Bedrift/Tjenester+og+skjemaer/Aa-registeret+og+a-meldingen">Her finner du mer informasjon om Arbeidsgiver- og arbeidstakerregisteret</a>.</p>`,
  "arbeidsforhold.kilde": `Kilde: Arbeidsgiver- og arbeidstakerregisteret</br><span style="text-transform: none;">Dataene er rapportert av arbeidsgiver</span>`,
  "arbeidsforhold.disclaimer": `Oversikten viser alle arbeidsforhold rapportert etter 01.01.2015.<br/>Hvis det er feil i et arbeidsforhold, kan arbeidsgiveren endre gjennom a-meldingen.`,
  "arbeidsforhold.submitted.by": `Dataene er rapportert av arbeidsgiver`,
  "utbetalinger.tittel": "Kontonummer for utbetaling",
  "utbetalinger.hjelpetekster.kontonummer": `<p>Når du mottar ytelser fra NAV må du oppgi en bankkonto som står i ditt navn. Adressen som NAV har registrert på deg må være lik den du har oppgitt til den utenlandske banken. </p><p>Du må oppgi IBAN for utbetaling til europeiske banker. Også noen land utenfor Europa bruker IBAN. IBAN starter med en landkode med to store bokstaver uten mellomrom. Deretter følger mellom 15 og 31 karakterer, antallet varierer mellom landene. .</p><p>Oppgir du IBAN-nummer, må du oppgi BIC.</p><p>Kontonummer som ikke er IBAN, kan ha BIC.</p>`,
  "utbetalinger.hjelpetekster.bic": `<p>BIC/SWIFT er et internasjonalt system som brukes for å identifisere banker. Du får oppgitt BIC av banken din. BIC/SWIFT-koden består av 8 eller 11 bokstaver.</p><p>Har du en europeisk bankkonto må du oppgi både BIC-kode og IBAN.</p><p>Hvis landet bruker bankkode, skal du oppgi BIC for de bankene som har BIC.</p>`,
  "utbetalinger.hjelpetekster.valuta": `<p>Gebyrene kan bli lavere hvis du velger utbetaling i  valutaen til landet du har bosatt deg i. Sjekk med banken hva som lønner seg. Har du en konto som er knyttet til en bestemt valuta (valutakonto), oppgir du denne valutaen til NAV.</p><p>Finner du ikke valutaen på listen, kan du velge en hovedvaluta: Amerikanske dollar (USD) eller euro (EUR).</p>`,
  "utbetalinger.hjelpetekster.bankkode": `<p>I dette feltet fyller du ut bankkode, fedwire number (FW) eller routing number.</p><p>Oppgir du en bankkode, trenger du ikke oppgi IBAN-nummer. Du oppgir BIC for de bankene som har det.</p><p>Land som bruker bankkode, er blant annet USA, Australia, Canada, Russland, New Zealand og Sør-Afrika.</p>`,
  "kontaktinfo.tittel": "Kontaktinformasjon",
  "dsop.tittel": `Utlevering av personopplysninger`,
  "dsop.levertedata": `Leverte data`,
  "dsop.kilde": `Kilde: Digital Sammhandling Offentlig og Privat`,
  "dsop.uthentingstidspunkt": "Uthentingstidspunkt",
  "dsop.personnummer": "Personnummer",
  "dsop.mottaker": "Mottaker",
  "dsop.tema": "Tema",
  "dsop.behanglingsGrunnlag": "Behandlingsgrunnlag",
  "dsop.lastned": "Last ned leverte data",
  "dsop.ingendata":
    "Dette er en logg som viser hvilke opplysninger vi har utlevert til forsikringsselskap basert på samtykke du har gitt på Altinn. Ingen personopplysninger har blitt utlevert.",
  "inst.tittel": `Institusjonsopphold`,
  "inst.detaljer": `Detaljer`,
  "inst.periode": `Periode`,
  "inst.institusjonsnavn": "Institusjonsnavn",
  "inst.institusjonstype": "Institusjonstype",
  "inst.registreringstidspunkt": "Registreringstidspunkt",
  "inst.ingendata": "Ingen institusjonsopphold er registrert",
  "skattetreksmeldinger.tittel": `Skattetreksmeldinger`,
  "skattetreksmeldinger.ingendata":
    "Ingen skattetreksmeldinger har blitt innhentet",
  "medl.tittel": `Medlemskap i folketrygden`,
  "medl.ingendata": "Ingen medlemskap i folketrygden",
  "dittnavkontor.tittel": `Ditt NAV&#8209;kontor`,
  "dittnavkontor.beskrivelse": `Hvis du allerede får oppfølging ved et NAV-kontor, skal du fortsette å bruke dette kontoret. Hvis du ikke får oppfølging, kan du bruke kontoret under.`,
  "dittnavkontor.ingress": `Ditt kontor er `,
  "dittnavkontor.postadresse": `Postadresse`,
  "dittnavkontor.postboks": `Postboks`,
  "dittnavkontor.publikumsmottak": `Publikumsmottak`,
  "dittnavkontor.publikumsmottakfor": `Publikumsmottak for`,
  "dittnavkontor.apningstider": `Åpningstider`,
  "dittnavkontor.andreapningstider": `Andre åpningertider`,
  "dittnavkontor.kontaktinfo.kontaktsenter.tittel": `Telefonnummer NAV Kontaktsenter`,
  "dittnavkontor.kontaktinfo.kontaktsenter.tlfnr": `<a class="lenke" href="tel:004755553333"/>55 55 33 33</a>`,
  "dittnavkontor.kontaktinfo.pensjon": `Pensjon`,
  "dittnavkontor.kontaktinfo.pensjon.tlfnr": `<a class="lenke" href="tel:004755553334"/>55 55 33 34</a> `,
  "dittnavkontor.kontaktinfo.apningstider.tittel": `Åpningstider på telefon`,
  "dittnavkontor.kontaktinfo.apningstider.innhold": `08.00 til 15.30 på hverdager.`,
  "dittnavkontor.kilde": `Folkeregisteret`,
  "lenker.tittel": `Flere opplysninger om deg`,
  "lenker.beskrivelse": `Vi har også opplysninger om deg som du ikke ser på denne siden. Gå til de ulike tjenestene under og se opplysninger.`,
  "lenker.pensjon.tittel": `Pensjonsopptjening`,
  "lenker.pensjon.beskrivelse": `Se din pensjonsopptjening og beregn alderspensjonen din.`,
  "lenker.pensjon.lenkeTekst": `Gå til Din pensjon`,
  "lenker.sykefravaer.tittel": `Ditt sykefravær`,
  "lenker.sykefravaer.beskrivelse": `Se sykefraværet og sykmeldingene dine.`,
  "lenker.sykefravaer.lenkeTekst": `Dine saker`,
  "lenker.dinesaker.tittel": `Dine saker`,
  "lenker.dinesaker.beskrivelse": `Se sakene og dokumentene dine, og din kommunikasjon med NAV.`,
  "lenker.dinesaker.lenkeTekst": `Gå til saksoversikt`,
  "lenker.utbetalinger.tittel": `Utbetalinger`,
  "lenker.utbetalinger.beskrivelse": `Se dine utbetalinger fra NAV (utbetalinger fra kommunen vises ikke).`,
  "lenker.utbetalinger.lenkeTekst": `Gå til utbetalinger`,
  "lenker.cv.tittel": `CV og stillingssøk`,
  "lenker.cv.beskrivelse": `Se CV-en og jobbprofilen din, og dine lagrede søk på stillinger.`,
  "lenker.cv.lenkeTekst": `Gå til CV/stillingssøk`,
  "lenker.dsop.tittel": `Utlevering av personopplysninger`,
  "lenker.dsop.beskrivelse": `Se hvilke opplysninger NAV kan gi til forsikringsselskap, fordi du har gitt samtykke.`,
  "lenker.dsop.lenkeTekst": `Gå til utlevering av personopplysninger`,
  "lenker.dsop.info": `Dette er en logg som viser hvilke opplysninger vi har utlevert til forsikringsselskap basert på samtykke du har gitt på Altinn. <a href="https://altinn.no">Se samtykket i Altinn.</a>`,
  "lenker.inst.tittel": `Institusjonsopphold`,
  "lenker.inst.beskrivelse": `Oversikt over dine institusjonsopphold`,
  "lenker.inst.lenkeTekst": `Gå til utlevering av institusjonsopphold`,
  "lenker.inst.info": `Dette er en logg som viser hvilke opplysninger vi har utlevert til forsikringsselskap basert på samtykke du har gitt på Altinn. <a href="https://altinn.no">Se samtykket i Altinn.</a>`,
  "lenker.skattetreksmelding.tittel": `Skattetreksmeldinger`,
  "lenker.skattetreksmelding.beskrivelse": `Oversikt over dine skattetreksmeldinger`,
  "lenker.skattetreksmelding.lenkeTekst": `Gå til skattetreksmeldinger`,
  "lenker.medl.tittel": `Medlemskap i folketrygden`,
  "lenker.medl.beskrivelse": `Oversikt over når du har vært medlem i folketrygden`,
  "lenker.medl.lenkeTekst": `Gå til medlemskap i folketrygden`,
  "lenker.fullmakt.tittel": `Fullmakter`,
  "lenker.fullmakt.beskrivelse": `Oversikt over dine fullmakter`,
  "lenker.fullmakt.lenkeTekst": `Gå til fullmakter`,
  "felter.type.label": "Type",
  "felter.type.velg": "Velg type",
  "felter.landkode.label": "Landkode",
  "felter.tlfnr.label": "Telefonnummer",
  "felter.adressetype": "Type adresse",
  "felter.adressetype.gateadresse": "Gateadresse",
  "felter.adressetype.postboksadresse": "Postboksadresse",
  "felter.adressetype.stedsadresse": "Stedsadresse",
  "felter.adressevalg.norsk": "Norsk adresse",
  "felter.adressevalg.utenlandsk": "Utenlandsk adresse",
  "felter.tilleggslinje.label": "C/O (valgfri)",
  "felter.tilleggslinje.placeholder": " ",
  "felter.gatenavn.label": "Gatenavn",
  "felter.gatenummer.label": "Nummer",
  "felter.gatebokstav.label": "Bokstav",
  "felter.bolignummer.label": "Bolignummer",
  "felter.gyldigtom.label": "Gyldig til",
  "felter.postnummer.label": "Postnummer",
  "felter.postboksnummer.label": "Postboksnummer",
  "felter.postboksanlegg.label": "Postboksanlegg",
  "felter.stedsadresse.label": "Stedsadresse",
  "felter.adresse.label": "Adresse",
  "felter.bankens.adresse.label": "Bankens adresse (valgfri)",
  "felter.land.label": "Land",
  "felter.kontonummer.label": "Kontonummer",
  "felter.kontonummervalg.norsk": "Norsk kontonummer",
  "felter.kontonummervalg.utenlandsk": "Utenlandsk kontonummer",
  "felter.utenlandskkonto.info": `Vær nøye med utfylling av bankinformasjon for utenlandsk konto slik at betalingen kommer frem til riktig sted. NAV er ikke ansvarlig for at opplysningene er riktige. Gebyrer kan påløpe. Les mer om krav til <a href="https://www.nav.no/no/NAV+og+samfunn/Kontakt+NAV/Utbetalinger/Utbetalinger/utbetaling-av-ytelser-fra-nav-til-utlandet"> utenlandsk kontonummer </a>.`,
  "felter.kontonummer.kontonummer.label": "Kontonummer / IBAN",
  "felter.bic.label": "BIC / Swift-kode",
  "felter.bankensland.label": "Bankens land",
  "felter.valuta.label": "Valuta",
  "felter.bankkode.label": "Bankkode",
  "felter.banknavn.label": "Bankens navn",
  "felter.bankidentifier.bic": "BIC / Swift-kode",
  "felter.bankidentifier.bankkode": "Bankkode",
  "felter.bankidentifier.harikke.bic": `Har ikke BIC / Swift-kode`,
  "felter.bankidentifier.harikke.bic.advarsel": `Dersom du ikke oppgir BIC / Swift-kode kan utbetalingen bli forsinket eller avvist.`,
  "felter.landetbrukerbankkode.advarsel": `For <span class="capitalize">{land}</span> kan du oppgi både BIC/Swift-kode og bankkode. Du kan oppgi begge, men det er tilstrekkelig med en av kodene.`,
  "validation.only.letters": "Skriv bare bokstaver",
  "validation.only.digits": "Skriv bare tall",
  "validation.only.digits.space": "Skriv bare tall og mellomrom",
  "validation.only.letters.and.digits": "Skriv bare bokstaver og tall",
  "validation.only.letters.space.and.digits": `Skriv bare bokstaver, mellomrom og tall`,
  "validation.min.one.letter": "Skriv minst en bokstav",
  "validation.without.space": "Mellomrom er ikke tillatt",
  "validation.gatenavn.pakrevd": "Gatenavn er nødvendig",
  "validation.gatenavn.valid": "Skriv bare bokstaver og punktum",
  "validation.husnummer.pakrevd": "Nødvendig",
  "validation.husnummer.positive": "Ugyldig",
  "validation.type.pakrevd": "Type er nødvendig",
  "validation.tlfnr.pakrevd": "Telefonnummer er nødvendig",
  "validation.tlfnr.siffer": "Telefonnummer må være tall",
  "validation.tlfnr.norske": "Norske telefonnummer må ha 8 tall",
  "validation.tlfnr.makslengde": "Telefonnummeret kan ha maksimalt 16 tall",
  "validation.retningsnr.pakrevd": "Retningsnummer er nødvendig",
  "validation.postnummer.pakrevd": "Bolignummer er nødvendig",
  "validation.postboksnummer.pakrevd": "Nødvendig",
  "validation.tomdato.pakrevd": "Gyldig dato er nødvendig",
  "validation.tomdato.ugyldig": "Ugyldig dato",
  "validation.gateadresse.pakrevd": "Gateadresse er nødvendig",
  "validation.stedsadresse.pakrevd": "Stedsadresse er nødvendig",
  "validation.land.pakrevd": "Land er nødvendig",
  "validation.bankidentifier.pakrevd": "Du må velge et alternativ",
  "validation.bankidentifier.valid": `Dersom du fyller ut IBAN-nummer, må du også fylle ut BIC / Swift-kode`,
  "validation.kontonummer.pakrevd": "Kontonummer er nødvendig",
  "validation.kontonummer.siffer": "Kontonummer må være tall",
  "validation.kontonummer.elleve": `Norske kontonummer må ha 11 tall`,
  "validation.kontonummer.mod11": `Skriv inn et gyldig kontonummer`,
  "validation.ikke.iban": `Amerikanske kontonummer kan ikke være IBAN`,
  "validation.iban.pakrevd": "Gyldig IBAN er nødvendig",
  "validation.iban.country": `Du må taste inn et IBAN-nummer fra det landet du har valgt.`,
  "validation.banknavn.pakrevd": "Banknavn er nødvendig",
  "validation.bankkode.pakrevd": "Bankkode er nødvendig",
  "validation.bankkode.lengde": `Bankkoder fra {land} må ha {siffer} tall`,
  "validation.bic.pakrevd": "BIC / Swift-kode er nødvendig",
  "validation.bic.gyldig": "Gyldig BIC / Swift-kode er nødvendig",
  "validation.bic.country": `Du må taste inn en gyldig BIC / Swift-kode fra det landet du har valgt.`,
  "validation.valuta.pakrevd": "Valuta er nødvendig",
  "validation.adresse.pakrevd": "Adresse er nødvendig",
  "validation.svarteliste.felles": `Kan ikke inneholde ord som "ukjent" og "vet ikke"`,
  "validation.bolignummer.ugyldig": `Bolignummer består av en bokstav (L, H, U eller K) og fire tall.`,
  "validation.firstchar.notspace": `Første bokstav kan ikke være mellomrom`,
  "alternativer.tittel": `Mer informasjon`,
  "alternativer.feilopplysninger.tittel": merInfo.feilopplysninger.tittel,
  "alternativer.feilopplysninger.melding": merInfo.feilopplysninger.melding,
  "alternativer.savneropplysninger.tittel": merInfo.savneropplysninger.tittel,
  "alternativer.savneropplysninger.melding": merInfo.savneropplysninger.melding,
  "alternativer.utlevere.tittel": merInfo.utlevere.tittel,
  "alternativer.utlevere.melding": merInfo.utlevere.melding,
  "alternativer.klage.tittel": merInfo.klage.tittel,
  "alternativer.klage.melding": merInfo.klage.melding
};
