import merInfo from "./nb/informasjon";
/* tslint:disable */
export default {
  "side.tittel": `Personopplysninger`,
  "brodsmulesti.dittnav": `Ditt NAV`,
  "brodsmulesti.dinepersonopplysninger": `Personopplysninger`,
  "brodsmulesti.arbeidsforhold": `Arbeidsforhold`,
  "header.hello": `Hei {name}!`,
  "header.description": `<a href='https://www.nav.no/personvern' target='blank' rel='noopener noreferrer' class='lenke'>Les om personvern i Arbeids- og velferdsetaten her.</a>`,
  "header.obs": `Her kan du se opplysninger som NAV har registrert om deg. Du har rett til innsyn i personopplysninger NAV har registrert om deg, men det er ikke sikkert du finner alle personopplysninger her. Det kan skyldes både tekniske og juridiske begrensninger.`,
  "personalia.tittel": `Personalia`,
  "personalia.beskrivelse": `Vi må vite hvem du er og hvordan vi kan kontakte deg. Hvis du skal ha tjenester eller søker om økonomisk støtte, trenger vi opplysninger for å kunne vurdere hva du har krav på. For å kunne utbetale penger trenger vi kontonummeret ditt og en adresse.`,
  "personalia.first_name": `Fornavn`,
  "personalia.first_and_middle_name": `For- og mellomnavn`,
  "personalia.surname": `Etternavn`,
  "personalia.fnr": `Fødselsnummer`,
  "personalia.dnr": `D-nummer`,
  "personalia.foreign_id": `Utenlandsk ID`,
  "personalia.email": `E-post`,
  "personalia.language": `Språk`,
  "personalia.citizenship": `Statsborgerskap`,
  "personalia.status": `Personstatus`,
  "personalia.birthplace": `Fødested`,
  "personalia.spesreg": `Spesialregistrering`,
  "personalia.civil_status": `Sivilstand`,
  "personalia.security_measure": `Sikkerhetstiltak`,
  "personalia.gender": `Kjønn`,
  "personalia.customized_comm": `Tilpasset kommunikasjon`,
  "personalia.source.folkeregisteret": `Kilde: Folkeregisteret`,
  "personalia.source.nav": `Kilde: NAV`,
  "personalia.source.dkif": `Kilde: Kontakt - og reservasjonsregisteret`,
  "personalia.link.folkeregisteret": `Endre i Folkeregisteret`,
  "personalia.link.brukerprofil.endre": `Endre i Din profil`,
  "personalia.link.brukerprofil.leggtil": `Legg til i Din profil`,
  "personalia.link.dkif.endre": `Endre i Kontakt- og reservasjonsregisteret `,
  "personalia.link.dkif.leggtil": `Gå til Kontakt- og reservasjonsregisteret `,
  "personalia.kontonr": `Kontonummer`,
  "personalia.kontonrelleriban": `Kontonummer/IBAN`,
  "personalia.kontonr.oveskrift": `Kontonummer vi utbetaler til`,
  "personalia.kontonr.ingenData": `Vi har ikke registrert kontonummer på deg. <br>Du kan registrere kontonummer via Din profil.`,
  "personalia.bank": `Bank`,
  "personalia.valuta": `Valuta`,
  "personalia.swiftkode": `BIC/SWIFT-kode`,
  "personalia.bankkode": `Bankkode`,
  "personalia.tlfnr": `Telefon`,
  "personalia.tlfnr.oveskrift": `Telefonnummer registrert hos NAV`,
  "personalia.tlfnr.ingenData": `Vi har ikke registrert telefonnummer på deg i våre registre. <br>Har du et telefonummer vi kan kontakte deg på?`,
  "personalia.tlfnr.jobb": `Jobb`,
  "personalia.tlfnr.privat": `Privat`,
  "personalia.tlfnr.mobil": `Mobil`,
  "personalia.dkif.overskrift": `Opplysninger fra Kontakt - og reservasjonsregisteret`,
  "personalia.dkif.beskrivelse": `Kontakt- og reservasjonsregisteret er et felles nasjonalt register. NAV må ha dine kontaktopplysninger i dette registeret for å kunne sende deg meldinger og dokumenter elektronisk.`,
  "personalia.dkif.kanVarsles": `Du har <b>ikke</b> reservert deg mot elektronisk kommunikasjon.`,
  "personalia.dkif.kanIkkeVarsles": `Du har reservert deg mot elektronisk kommunikasjon.`,
  "personalia.dkif.ingenData": `Ingen opplysninger registrert`,
  "adresse.tittel": `Adresser`,
  "adresse.beskrivelse": `Her finner du bostedsadresse og eventuelt din midlertidige adresse.`,
  "adresse.bostedsadresse": `Bostedsadresse`,
  "adresse.bostedsadresse.apneTekst": `Vis detaljer`,
  "adresse.bostedsadresse.lukkTekst": `Skjul detaljer`,
  "adresse.midlertidigadresse": `Midlertidig adresse`,
  "adresse.midlertidigadresse.leggtil.beskrivelse": `Du har ikke registrert en midlertidig adresse. <br>Hvis du ønsker å få post fra NAV til en midlertidig adresse, kan du registrere adressen.`,
  "adresse.utenlandskadresse": `Midlertidig adresse i utlandet`,
  "adresse.utenlandskadresse.leggtil.beskrivelse": `Du har ikke registrert en midlertidig adresse. <br>Hvis du ønsker å få post fra NAV til en midlertidig adresse, kan du registrere adressen. `,
  "adresse.postadresse": `Postadresse`,
  "adresse.adressetillegg": `Adressetillegg`,
  "adresse.gate": `Gate`,
  "adresse.postnummer": `Postnummer`,
  "adresse.poststed": `Poststed`,
  "adresse.dato": `Flyttedato`,
  "adresse.kommune": `Kommune`,
  "adresse.bolignummer": `Bolignummer`,
  "adresse.land": `Land`,
  "adresse.ikke.registrert": `Du har ikke registrert bostedsadresse i Folkeregisteret.`,
  "arbeidsforhold.tittel": `Arbeidsforhold`,
  "arbeidsforhold.beskrivelse": `<p>NAV trenger informasjon om arbeidsforholdene dine for å kunne vurdere behovet ditt for oppfølging og tjenester fra NAV, og til å beregne ytelser hvor mye du kan få utbetalt i for eksempel sykepenger, dagpenger og foreldrepenger. Andre offentlige etater har også tilgang til opplysninger fra Arbeidsgiver og arbeidstakerregisteret.</p><p>Det er Arbeids- og velferdsetaten som eier og forvalter Arbeidsgiver og arbeidstakerregisteret.<br/><a href="https://www.nav.no/no/Bedrift/Tjenester+og+skjemaer/Aa-registeret+og+a-meldingen/Hva+er+er+Aa-registeret">Her finner du mer informasjon om Arbeidsgiver- og arbeidstakerregisteret (Aa-registeret)</a>.</p>`,
  "arbeidsforhold.kilde": "Kilde: Arbeidsgiver- og arbeidstakerregisteret",
  "arbeidsforhold.disclaimer": `Oversikten viser alle arbeidsforhold rapportert etter 01.01.2015.<br/>Dersom det avdekkes feil, må dette rettes i a-meldingen av arbeidsgiver.`,
  "arbeidsforhold.submitted.by": `Dataene er rapportert av arbeidsgiver`,
  "utbetalinger.tittel": "Kontonummer for utbetaling",
  "kontaktinfo.tittel": "Kontaktinformasjon",
  "dsop.tittel": `Utlevering av persondata`,
  "dsop.kilde": `Kilde: Digital Sammhandling Offentlig og Privat`,
  "dsop.uthentingstidspunkt": "Uthentingstidspunkt",
  "dsop.personnummer": "Personnummer",
  "dsop.tema": "Tema",
  "dsop.behanglingsGrunnlag": "Behandlingsgrunnlag",
  "dittnavkontor.tittel": `Ditt NAV-kontor`,
  "dittnavkontor.beskrivelse": `Hvis du allerede får oppfølging ved et NAV-kontor, skal du fortsette å bruke dette kontoret. Hvis du ikke får oppfølging, kan du bruke kontoret under.`,
  "dittnavkontor.ingress": `Ditt kontor er `,
  "dittnavkontor.postadresse": `Postadresse`,
  "dittnavkontor.postboks": `Postboks`,
  "dittnavkontor.publikumsmottak": `Publikumsmottak`,
  "dittnavkontor.publikumsmottakfor": `Publikumsmottak for`,
  "dittnavkontor.apningstider": `Åpningstider`,
  "dittnavkontor.andreapningstider": `Andre åpningertider`,
  "dittnavkontor.kontaktinfo.kontaktsenter.tittel": `Telefonnummer NAV Kontaktsenter`,
  "dittnavkontor.kontaktinfo.kontaktsenter.tlfnr": `<a class="lenke" href="tel:004755553333"/>55 55 33 33</a>`,
  "dittnavkontor.kontaktinfo.pensjon": `Pensjon`,
  "dittnavkontor.kontaktinfo.pensjon.tlfnr": `<a class="lenke" href="tel:004755553334"/>55 55 33 34</a> `,
  "dittnavkontor.kontaktinfo.apningstider.tittel": `Åpningstider på telefon`,
  "dittnavkontor.kontaktinfo.apningstider.innhold": `08.00 til 15.30 på hverdager.`,
  "dittnavkontor.kilde": `Folkeregisteret`,
  "eksternelenker.tittel": `Flere opplysninger på Ditt NAV`,
  "eksternelenker.beskrivelse": `Vi har også opplysninger om deg som ikke vises på denne siden. De opplysningene kan du finne ved å gå til de ulike tjenestene under.`,
  "eksternelenker.pensjon.tittel": `Pensjonsopptjening`,
  "eksternelenker.pensjon.beskrivelse": `Oversikt over din pensjonsopptjening`,
  "eksternelenker.pensjon.lenkeTekst": `Gå til Din pensjon`,
  "eksternelenker.sykefravaer.tittel": `Ditt sykefravær`,
  "eksternelenker.sykefravaer.beskrivelse": `Oversikt over dine sykemeldinger`,
  "eksternelenker.sykefravaer.lenkeTekst": `Dine saker`,
  "eksternelenker.dinesaker.tittel": `Dine saker`,
  "eksternelenker.dinesaker.beskrivelse": `Oversikt over dine saker og kommunikasjon med NAV`,
  "eksternelenker.dinesaker.lenkeTekst": `Gå til saksoversikt`,
  "eksternelenker.utbetalinger.tittel": `Utbetalinger`,
  "eksternelenker.utbetalinger.beskrivelse": `Oversikt over dine utbetalinger`,
  "eksternelenker.utbetalinger.lenkeTekst": `Gå til utbetalinger`,
  "eksternelenker.cv.tittel": `CV og stillingssøk`,
  "eksternelenker.cv.beskrivelse": `Oversikt over din CV og lagrede stillingssøk`,
  "eksternelenker.cv.lenkeTekst": `Gå til CV/stillingssøk`,
  "eksternelenker.dsop.tittel": `Utlevering av persondata`,
  "eksternelenker.dsop.beskrivelse": `Oversikt over dine persondata som utleveres til eksterne virkesomhet`,
  "eksternelenker.dsop.lenkeTekst": `Gå til utlevering av persondata`,
  "alternativer.tittel": `Mer informasjon`,
  "alternativer.feilopplysninger.tittel": merInfo.feilopplysninger.tittel,
  "alternativer.feilopplysninger.melding": merInfo.feilopplysninger.melding,
  "alternativer.savneropplysninger.tittel": merInfo.savneropplysninger.tittel,
  "alternativer.savneropplysninger.melding": merInfo.savneropplysninger.melding,
  "alternativer.utlevere.tittel": merInfo.utlevere.tittel,
  "alternativer.utlevere.melding": merInfo.utlevere.melding,
  "alternativer.klage.tittel": merInfo.klage.tittel,
  "alternativer.klage.melding": merInfo.klage.melding
};
