export default {
  adresseinfo: {
    boadresse: {
      adresse: '',
      adressetillegg: '',
      bydel: '',
      datoFraOgMed: '',
      kilde: '',
      kommune: '',
      landkode: '',
      matrikkeladresse: {
        bruksnummer: '',
        festenummer: '',
        gaardsnummer: '',
        undernummer: '',
      },
      postnummer: '',
      veiadresse: {
        bokstav: '',
        bolignummer: '',
        gatekode: '',
        husnummer: '',
      },
    },
    geografiskTilknytning: {
      bydel: '',
      datoFraOgMed: '',
      kilde: '',
      kommune: '',
      land: '',
    },
    postadresse: '',
    prioritertAdresse: '',
    tilleggsadresse: '',
    utenlandskAdresse: '',
  },
  barnListe: [
    {
      datoRegistert: '',
      egenansatt: null,
      fnr: '',
      kilde: '',
      spesreg: '',
    },
  ],
  brukerbehovListe: [
    {
      behov: '',
      datoFraOgMed: '',
      kilde: '',
    },
  ],
  datoFraOgMed: '',
  doedsdato: {
    dato: '',
    datoFraOgMed: '',
    kilde: '',
  },
  egenansatt: {
    datoFraOgMed: '',
    erEgenansatt: null,
    kilde: '',
  },
  foedselsdato: '',
  foedtIKommune: '',
  foedtILand: '',
  foreldreansvar: {
    datoFraOgMed: '',
    kilde: '',
    type: '',
  },
  ident: '',
  identtype: {
    kodeverk: '',
    verdi: '',
  },
  innvandringUtvandring: {
    innvandretDato: '',
    innvandretKilde: '',
    innvandretLand: {
      kodeverk: '',
      verdi: '',
    },
    utvandretLand: {
      kodeverk: '',
      verdi: '',
    },
    utvandretKilde: '',
  },
  kilde: '',
  kjonn: '',
  kontonummer: {
    datoFraOgMed: '',
    kilde: '',
    nummer: '',
  },
  navn: {
    datoFraOgMed: '',
    forkortetNavn: '',
    fornavn: '',
    kilde: '',
    mellomnavn: '',
    slektsnavn: '',
    slektsnavnUgift: '',
  },
  oppholdstillatelse: {
    datoFraOgMed: '',
    kilde: '',
    type: '',
  },
  relasjon: {
    datoFraOgMed: '',
    egenansatt: null,
    fnr: '',
    kilde: '',
    spesreg: '',
    type: '',
  },
  samboer: {
    datoFraOgMed: '',
    fnr: '',
    kilde: '',
  },
  sivilstand: {
    datoFraOgMed: '',
    kilde: '',
    kode: {
      kodeverk: '',
      verdi: '',
    },
  },
  spesreg: {
    datoFraOgMed: '',
    kilde: '',
    kode: {
      kodeverk: '',
      verdi: '',
    },
  },
  spraak: {
    datoFraOgMed: '',
    kilde: '',
    kode: {
      kodeverk: '',
      verdi: '',
    },
  },
  statsborgerskap: {
    datoFraOgMed: '',
    kilde: '',
    kode: {
      kodeverk: '',
      verdi: '',
    },
  },
  status: {
    datoFraOgMed: '',
    kilde: '',
    kode: {
      kodeverk: '',
      verdi: '',
    },
  },
  telefon: {
    jobb: '',
    jobbDatoRegistrert: '',
    jobbKilde: '',
    mobil: '',
    mobilDatoRegistrert: '',
    mobilKilde: '',
    privat: '',
    privatDatoRegistrert: '',
    privatKilde: '',
  },
  tiltak: {
    datoFraOgMed: '',
    datoTil: '',
    kilde: '',
    type: '',
  },
  utenlandsinfoList: [
    {
      datoFraOgMed: '',
      familienavnFodt: '',
      farsFamilenavn: '',
      farsFornavn: '',
      foedested: '',
      fornavnFodt: '',
      idOff: '',
      institusjon: '',
      institusjonNavn: '',
      kilde: '',
      kildePin: '',
      land: '',
      morsFamilenavn: '',
      morsFornavn: '',
      nasjonalId: '',
      nasjonalitet: '',
      sedRef: '',
      sektor: '',
    },
  ],
  utenlandskBank: {
    adresse1: '',
    adresse2: '',
    adresse3: '',
    bankkode: '',
    banknavn: '',
    datoFraOgMed: '',
    iban: '',
    kilde: '',
    kontonummer: '',
    land: '',
    swiftkode: '',
    valuta: '',
  },
  vergemaalListe: [
    {
      aaksId: '',
      datoFraOgMed: '',
      egenansatt: null,
      embete: '',
      fnr: '',
      id: '',
      kilde: '',
      mandattype: '',
      sakstype: '',
      spesreg: '',
      type: '',
      vedtaksdato: '',
    },
  ],
};
