name: Deploy to dev
on:
  workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/build-and-deploy.yml
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    with:
      env: dev
      imageSuffix: dev-deploy
      appOrigin: "https://www.intern.dev.nav.no"
      REACT_APP_VERSION: "dev-${{ github.sha }}"
      REACT_APP_DINE_SAKER_URL: "https://www.intern.dev.nav.no/mine-saker"
      REACT_APP_PDL_URL: "https://www.intern.dev.nav.no/person/pdl-fullmakt-ui"
      REACT_APP_SKJERMING_URL: "https://skjerming-ui.intern.dev.nav.no/person/personopplysninger/skjerming"
      REACT_APP_URL: "https://www.intern.dev.nav.no/person/personopplysninger"
      REACT_APP_API_URL: "https://www.intern.dev.nav.no/person/personopplysninger-api"
      REACT_APP_DSOP_URL: "https://www.intern.dev.nav.no/person/dsop-api"
      REACT_APP_TJENESTER_URL: "https://tjenester-q1.nav.no"
      REACT_APP_LOGIN_URL: "https://login.ekstern.dev.nav.no/oauth2/login"
      REACT_APP_DITT_NAV_URL: "https://www.intern.dev.nav.no/minside"
      REACT_APP_PENSJONSOPPTJENING_URL: "https://www-q0.nav.no/pensjon/opptjening"
      REACT_APP_INNLOGGINGSSTATUS_URL: "https://www.ekstern.dev.nav.no/person/nav-dekoratoren-api/auth"
      REACT_APP_TELEMETRY_URL: "https://telemetry.ekstern.dev.nav.no/collect"
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
